const MOVIES = {
  trending: [
    {
      id: 1,
      title: "The Lion of the Savanna",
      year: 2024,
      rating: "PG-13",
      score: 8.4,
      duration: "2h 14m",
      genres: ["Action", "Adventure"],
      description:
        "A pride of lions battles rival clans across the vast Serengeti, led by a scarred but wise patriarch fighting to protect his family.",
      thumbnail: "https://picsum.photos/seed/lion/300/170",
      banner: "https://picsum.photos/seed/lion/1280/720",
    },
    {
      id: 2,
      title: "Nairobi Nights",
      year: 2023,
      rating: "R",
      score: 7.8,
      duration: "1h 58m",
      genres: ["Thriller", "Drama"],
      description:
        "A detective unravels a web of corruption that runs from the city streets to the highest offices in Nairobi.",
      thumbnail: "https://picsum.photos/seed/nairobi/300/170",
      banner: "https://picsum.photos/seed/nairobi/1280/720",
    },
    {
      id: 3,
      title: "Kilimanjaro",
      year: 2024,
      rating: "PG",
      score: 9.1,
      duration: "2h 32m",
      genres: ["Drama", "Inspiration"],
      description:
        "A young Tanzanian climber defies expectations and family tradition to become the first in her village to summit Africa's highest peak.",
      thumbnail: "https://picsum.photos/seed/kilimanjaro/300/170",
      banner: "https://picsum.photos/seed/kilimanjaro/1280/720",
    },
    {
      id: 4,
      title: "Zanzibar Blue",
      year: 2023,
      rating: "PG",
      score: 7.5,
      duration: "1h 47m",
      genres: ["Romance", "Drama"],
      description:
        "Two strangers meet on the shores of Zanzibar and discover a connection that transcends language, culture, and time.",
      thumbnail: "https://picsum.photos/seed/zanzibar/300/170",
      banner: "https://picsum.photos/seed/zanzibar/1280/720",
    },
    {
      id: 5,
      title: "Masai Warriors",
      year: 2022,
      rating: "PG-13",
      score: 8.0,
      duration: "2h 05m",
      genres: ["Action", "History"],
      description:
        "The untold story of Maasai warriors who resisted colonial expansion through courage, strategy, and community.",
      thumbnail: "https://picsum.photos/seed/masai/300/170",
      banner: "https://picsum.photos/seed/masai/1280/720",
    },
    {
      id: 6,
      title: "Dar es Salaam Express",
      year: 2024,
      rating: "R",
      score: 7.3,
      duration: "1h 54m",
      genres: ["Action", "Thriller"],
      description:
        "A rogue agent must stop a runaway train loaded with stolen cargo before it derails into the heart of Dar es Salaam.",
      thumbnail: "https://picsum.photos/seed/dares/300/170",
      banner: "https://picsum.photos/seed/dares/1280/720",
    },
  ],
  newReleases: [
    {
      id: 7,
      title: "Safari Dreams",
      year: 2025,
      rating: "G",
      score: 8.7,
      duration: "1h 38m",
      genres: ["Family", "Adventure"],
      description:
        "An animated journey following a group of young animals on their first migration across the Tanzanian plains.",
      thumbnail: "https://picsum.photos/seed/safari/300/170",
      banner: "https://picsum.photos/seed/safari/1280/720",
    },
    {
      id: 8,
      title: "The Dhow Builders",
      year: 2025,
      rating: "PG",
      score: 7.9,
      duration: "1h 52m",
      genres: ["Documentary", "History"],
      description:
        "A master dhow craftsman passes his ancient maritime tradition to his reluctant grandson in modern-day Lamu.",
      thumbnail: "https://picsum.photos/seed/dhow/300/170",
      banner: "https://picsum.photos/seed/dhow/1280/720",
    },
    {
      id: 9,
      title: "Coastal Storm",
      year: 2025,
      rating: "PG-13",
      score: 8.2,
      duration: "2h 08m",
      genres: ["Drama", "Disaster"],
      description:
        "A fishing community on Tanzania's coast must unite when a catastrophic cyclone threatens to destroy everything they know.",
      thumbnail: "https://picsum.photos/seed/coastal/300/170",
      banner: "https://picsum.photos/seed/coastal/1280/720",
    },
    {
      id: 10,
      title: "Rhythm of Africa",
      year: 2025,
      rating: "PG",
      score: 8.5,
      duration: "1h 42m",
      genres: ["Music", "Drama"],
      description:
        "A taarab musician from Zanzibar journeys across East Africa to record her debut album before illness takes her voice.",
      thumbnail: "https://picsum.photos/seed/rhythm/300/170",
      banner: "https://picsum.photos/seed/rhythm/1280/720",
    },
    {
      id: 11,
      title: "Ghost of Olduvai",
      year: 2025,
      rating: "PG-13",
      score: 7.6,
      duration: "1h 59m",
      genres: ["Mystery", "Sci-Fi"],
      description:
        "An archaeologist discovers an artifact at Olduvai Gorge that blurs the boundary between ancient history and present danger.",
      thumbnail: "https://picsum.photos/seed/olduvai/300/170",
      banner: "https://picsum.photos/seed/olduvai/1280/720",
    },
    {
      id: 12,
      title: "Mount Meru",
      year: 2025,
      rating: "PG",
      score: 8.1,
      duration: "2h 18m",
      genres: ["Adventure", "Survival"],
      description:
        "Two rival mountaineers are forced to work together after an earthquake traps them on Tanzania's second-highest mountain.",
      thumbnail: "https://picsum.photos/seed/meru/300/170",
      banner: "https://picsum.photos/seed/meru/1280/720",
    },
  ],
  topRated: [
    {
      id: 13,
      title: "The Serengeti Code",
      year: 2021,
      rating: "PG-13",
      score: 9.4,
      duration: "2h 45m",
      genres: ["Drama", "Mystery"],
      description:
        "A field biologist decoding animal migration patterns stumbles upon a century-old secret buried beneath the Serengeti.",
      thumbnail: "https://picsum.photos/seed/serengeti/300/170",
      banner: "https://picsum.photos/seed/serengeti/1280/720",
    },
    {
      id: 14,
      title: "Uhuru",
      year: 2019,
      rating: "PG-13",
      score: 9.2,
      duration: "3h 02m",
      genres: ["History", "Drama"],
      description:
        "An epic saga of Tanzania's journey to independence told through three generations of one family's sacrifices.",
      thumbnail: "https://picsum.photos/seed/uhuru/300/170",
      banner: "https://picsum.photos/seed/uhuru/1280/720",
    },
    {
      id: 15,
      title: "Pemba Island",
      year: 2020,
      rating: "R",
      score: 9.0,
      duration: "2h 21m",
      genres: ["Thriller", "Crime"],
      description:
        "On a remote island where secrets sink deeper than the ocean, a journalist risks everything to expose the truth.",
      thumbnail: "https://picsum.photos/seed/pemba/300/170",
      banner: "https://picsum.photos/seed/pemba/1280/720",
    },
    {
      id: 16,
      title: "Song of the Crater",
      year: 2022,
      rating: "PG",
      score: 8.9,
      duration: "1h 56m",
      genres: ["Romance", "Music"],
      description:
        "A blind composer writes the symphony of his life inspired by the sounds of Ngorongoro Crater during his final season there.",
      thumbnail: "https://picsum.photos/seed/crater/300/170",
      banner: "https://picsum.photos/seed/crater/1280/720",
    },
    {
      id: 17,
      title: "Warriors of the Rift",
      year: 2018,
      rating: "R",
      score: 8.8,
      duration: "2h 33m",
      genres: ["Action", "History"],
      description:
        "In the shadow of the Great Rift Valley, a band of rebels ignites a revolution that changes East Africa forever.",
      thumbnail: "https://picsum.photos/seed/rift/300/170",
      banner: "https://picsum.photos/seed/rift/1280/720",
    },
    {
      id: 18,
      title: "Baobab",
      year: 2023,
      rating: "PG",
      score: 8.6,
      duration: "1h 48m",
      genres: ["Family", "Fantasy"],
      description:
        "A girl discovers that the ancient baobab tree in her village is alive — and has been protecting her family for centuries.",
      thumbnail: "https://picsum.photos/seed/baobab/300/170",
      banner: "https://picsum.photos/seed/baobab/1280/720",
    },
  ],
  africanCinema: [
    {
      id: 19,
      title: "Lagos After Dark",
      year: 2023,
      rating: "R",
      score: 7.9,
      duration: "2h 02m",
      genres: ["Crime", "Thriller"],
      description:
        "When night falls in Lagos, a retired detective is pulled back into a world she swore to leave behind.",
      thumbnail: "https://picsum.photos/seed/lagos/300/170",
      banner: "https://picsum.photos/seed/lagos/1280/720",
    },
    {
      id: 20,
      title: "Nile Story",
      year: 2022,
      rating: "PG-13",
      score: 8.3,
      duration: "2h 15m",
      genres: ["Drama", "Adventure"],
      description:
        "Following the entire course of the Nile River, five interlinked stories explore love, loss, and survival.",
      thumbnail: "https://picsum.photos/seed/nile/300/170",
      banner: "https://picsum.photos/seed/nile/1280/720",
    },
    {
      id: 21,
      title: "Kalahari",
      year: 2024,
      rating: "PG",
      score: 7.7,
      duration: "1h 51m",
      genres: ["Survival", "Drama"],
      description:
        "A San family must cross the deadly Kalahari Desert on foot to reach the only doctor who can save their child.",
      thumbnail: "https://picsum.photos/seed/kalahari/300/170",
      banner: "https://picsum.photos/seed/kalahari/1280/720",
    },
    {
      id: 22,
      title: "Cape Town Confidential",
      year: 2023,
      rating: "R",
      score: 8.0,
      duration: "1h 58m",
      genres: ["Crime", "Mystery"],
      description:
        "A Cape Town detective hunts a serial art thief whose crimes hide a far deeper conspiracy.",
      thumbnail: "https://picsum.photos/seed/capetown/300/170",
      banner: "https://picsum.photos/seed/capetown/1280/720",
    },
    {
      id: 23,
      title: "Victoria Falls",
      year: 2024,
      rating: "PG",
      score: 8.4,
      duration: "2h 07m",
      genres: ["Romance", "Adventure"],
      description:
        "A travel photographer falls for her river guide during a dangerous expedition along the Zambezi.",
      thumbnail: "https://picsum.photos/seed/victoria/300/170",
      banner: "https://picsum.photos/seed/victoria/1280/720",
    },
    {
      id: 24,
      title: "Sahara Heist",
      year: 2024,
      rating: "PG-13",
      score: 7.5,
      duration: "2h 01m",
      genres: ["Action", "Comedy"],
      description:
        "A loveable band of thieves attempts to steal a priceless artifact from beneath the Sahara — and each other.",
      thumbnail: "https://picsum.photos/seed/sahara/300/170",
      banner: "https://picsum.photos/seed/sahara/1280/720",
    },
  ],
};

const HERO_MOVIE = MOVIES.trending[2]; // Kilimanjaro as the hero feature
